[package]
name = "powdr-guest"
version = "0.1.0"
edition = "2021"

[dependencies]
powdr-riscv-runtime = { path = "../../../../riscv-runtime", features = ["std"]}

serde = { version = "1.0", default-features = false, features = [
  "alloc",
  "derive",
  "rc",
] }

[workspace]
