[package]
name = "{{GUEST_NAME}}"
version = "0.1.0"
edition = "2021"

[dependencies]
powdr-riscv-syscalls = { git = "https://github.com/powdr-labs/powdr" }
powdr-riscv-runtime = { git = "https://github.com/powdr-labs/powdr", features = ["std"]}

[workspace]
