[workspace]
[package]
name = "powdr-openvm-guest-hints-test"
version = "0.0.0"
edition = "2021"

[dependencies]
# TODO: point hints-guest extension to github/main and remove the following `rev`
openvm = { git = "https://github.com/powdr-labs/openvm.git", rev = "acbd2ba" }
powdr-openvm-hints-guest = { path = "../extensions/hints-guest/" }

[profile.release-with-debug]
inherits = "release"
debug = true
