[workspace]
[package]
name = "powdr-openvm-guest-hints-test"
version = "0.0.0"
edition = "2021"

[dependencies]
# The `rev` here must point to the same version used in the workspace.
# Otherwise, there is conflict with the `powdr-openvm-hints-guest` dependency (which is part of the workspace).
openvm = { git = "https://github.com/powdr-labs/openvm.git", rev = "4908885" }
powdr-openvm-hints-guest = { path = "../extensions/hints-guest/" }

[profile.release-with-debug]
inherits = "release"
debug = true
