[workspace]
[package]
name = "powdr-openvm-guest-hints-test"
version = "0.0.0"
edition = "2021"

[dependencies]
# The `rev` here must point to the same version used in the workspace
openvm = { git = "https://github.com/powdr-labs/openvm.git", rev = "391b737" }
powdr-openvm-hints-guest = { path = "../extensions/hints-guest/" }

[profile.release-with-debug]
inherits = "release"
debug = true
