[package]
name = "openvm-primitives"
description = ""
version.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
eyre.workspace = true
serde_json.workspace = true
serde.workspace = true
tracing.workspace = true

# reth
reth-primitives.workspace = true
reth-revm.workspace = true
reth-trie.workspace = true
reth-chainspec.workspace = true

# revm
revm-interpreter.workspace = true
revm-precompile.workspace = true
revm-primitives.workspace = true

# alloy
alloy-hardforks.workspace = true
alloy-rpc-types.workspace = true
