name: "Patch openvm-reth-benchmark"
description: "Checks out powdr-labs/openvm-reth-benchmark at a fixed ref and patches it to use local powdr crates"

runs:
  using: "composite"
  steps:
    - name: Checkout openvm-reth-benchmark
      uses: actions/checkout@v4
      with:
        repository: powdr-labs/openvm-reth-benchmark
        # Set once here — no inputs required elsewhere
        # Should always point to the latest main commit
        ref: 4a458d77c3b85ab14926ac6d51d637ccb9bdc383
        path: openvm-reth-benchmark

    - name: Verify openvm-reth-benchmark ref is on main
      shell: bash
      run: |
        cd openvm-reth-benchmark
        if [ "$(git rev-parse --is-shallow-repository)" = "true" ]; then
          git fetch --quiet --unshallow origin main
        else
          git fetch --quiet origin main
        fi
        if ! git merge-base --is-ancestor HEAD origin/main; then
          echo "Pinned ref is not in origin/main history."
          echo "HEAD: $(git rev-parse HEAD)"
          echo "origin/main: $(git rev-parse origin/main)"
          exit 1
        fi

    - name: Patch openvm-reth-benchmark to use local powdr
      shell: bash
      run: |
        cd openvm-reth-benchmark
        mkdir -p .cargo
        cat <<'EOF' > .cargo/config.toml
        [patch."https://github.com/powdr-labs/powdr.git"]
        powdr-openvm = { path = "../openvm" }
        powdr-riscv-elf = { path = "../riscv-elf" }
        powdr-number = { path = "../number" }
        powdr-autoprecompiles = { path = "../autoprecompiles" }
        powdr-openvm-hints-circuit = { path = "../openvm/extensions/hints-circuit" }
        EOF
