[workspace]
[package]
name = "openvm-ecc-hint"
version = "0.0.0"
edition = "2021"

[dependencies]
openvm = { git = "https://github.com/powdr-labs/openvm.git", rev = "391b737" }
powdr-openvm-hints-guest = { path = "/home/shuang/PowdrCode/powdr7jul/powdr/openvm/extensions/hints-guest/" }
k256 = {version="0.13",default-features = false,features=["expose-field","arithmetic"]}
hex-literal = "1.0.0"
elliptic-curve = { version = "0.13.8", default-features = false, features = ["arithmetic"] }
crypto-bigint = { version = "0.6.1", default-features = false }