name: "Init testing instance (GPU)"
description: "Initialises a testing instance with all required tools and fetches the precomputed tests archive named `tests_archive_gpu`"

runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Download build artifacts (GPU)
        uses: actions/download-artifact@v4
        with:
          name: tests_archive_gpu
      - name: Install Rust toolchain nightly-2025-05-14 (with clippy and rustfmt)
        shell: bash
        run: rustup toolchain install nightly-2025-05-14 --component clippy,rustfmt,rust-src
      - name: Install riscv target
        shell: bash
        run: rustup target add riscv32imac-unknown-none-elf --toolchain nightly-2025-10-01
      # TODO: runner on our GPU server has no sudo access, so we manually installed these
      # - name: Install test dependencies
      #  shell: bash
      #  run: sudo apt-get update && sudo apt-get install -y binutils-riscv64-unknown-elf lld
      - name: Install Rust deps
        shell: bash
        run: rustup install nightly-2025-10-01 --component rust-src
      - name: Install Rust deps
        shell: bash
        run: rustup install nightly-2025-02-14 --component rust-src
      - name: Install OpenVM guest toolchain (nightly-2025-08-02)
        shell: bash
        run: |
          rustup toolchain install nightly-2025-08-02
          rustup component add rust-src --toolchain nightly-2025-08-02
      - uses: taiki-e/install-action@nextest


