[workspace]
[package]
name = "openvm-ecc-powdr-affine-add"
version = "0.0.0"
edition = "2021"

[dependencies]
openvm = { git = "https://github.com/powdr-labs/openvm.git", rev = "391b737" }
k256 = {git = "https://github.com/ShuangWu121/elliptic-curves.git",rev="a14e0094b6f3a56b825721a97292608695ba94f5",default-features = false,features=["expose-field","arithmetic"]}
hex-literal = "1.0.0"