[package]
name = "powdr-guest"
version = "0.1.0"
edition = "2021"

[dependencies]
powdr-riscv-runtime = { git = "https://github.com/powdr-labs/powdr", tag = "v0.1.3", features = [
  "std",
] }
tiny-keccak = { version = "2.0.2", features = ["keccak"] }

[workspace]
