[workspace]
[package]
name = "openvm-ecc-powdr-affine-add"
version = "0.0.0"
edition = "2021"

[dependencies]
openvm = { git = "https://github.com/powdr-labs/openvm.git", rev = "391b737" }
k256 = {path = "/home/shuang/PowdrCode/shuangEccCurve/elliptic-curves/k256",default-features = false,features=["expose-field","arithmetic"]}
hex-literal = "1.0.0"