[package]
name = "powdr-guest"
version = "0.1.0"
edition = "2021"

[dependencies]
powdr-riscv-syscalls = { path = "../../../riscv-syscalls" } #{ git = "https://github.com/powdr-labs/powdr", tag = "v0.1.2" }
powdr-riscv-runtime = { path = "../../../riscv-runtime", features = [ # { git = "https://github.com/powdr-labs/powdr", tag = "v0.1.2", features = [
  "std",
] }

[workspace]
