[package]
name = "fibonacci"
version = "0.1.0"
edition = "2021"

[features]
default = []
simd = ["powdr/plonky3-simd"]

[dependencies]
#powdr = { git = "https://github.com/powdr-labs/powdr", tag = "v0.1.3", features = [
powdr = { path = "../../powdr", features = [
  "plonky3",
] }

env_logger = "0.10.2"
log = "0.4.17"

[workspace]
