/*
 * C shim bridging Rust to the Leanr optimizer's `@[export] apc_optimizer_optimize_json`.
 *
 * Exposes a plain C ABI:
 *   char *leanr_optimize(const char *input);   // JSON in -> optimized JSON out (malloc'd)
 *   void  leanr_free(char *p);                  // free the returned buffer
 *
 * The Lean runtime is initialized exactly once (pthread_once). All calls are serialized with a
 * global mutex, and calls arriving on a thread other than the one that initialized the runtime
 * register/unregister that thread with the Lean runtime around the call. This makes the shim safe
 * under `cargo test`'s parallel test threads.
 */
#include <lean/lean.h>
#include <pthread.h>
#include <stdlib.h>
#include <string.h>

/*
 * Generated by Lean for module `ApcOptimizer.Ffi` in the `apc-optimizer` lib. The module-init
 * symbol embeds the lib name with Lean's name mangling (`-` -> `x2d`), and takes a single
 * `builtin` flag (no IO world) in this toolchain, matching the generated `Main.c`. If the Leanr
 * lib/module is renamed, these two symbols change accordingly.
 */
extern lean_object *apc_optimizer_optimize_json(lean_object *input);
extern lean_object *initialize_apc_x2doptimizer_ApcOptimizer_Ffi(uint8_t builtin);

/* Provided by libleanrt. */
extern void lean_initialize_runtime_module(void);
extern void lean_initialize_thread(void);
extern void lean_finalize_thread(void);

static pthread_once_t g_init_once = PTHREAD_ONCE_INIT;
static pthread_mutex_t g_call_lock = PTHREAD_MUTEX_INITIALIZER;
static pthread_t g_init_thread;

static void leanr_do_init(void) {
    lean_initialize_runtime_module();
    lean_object *res = initialize_apc_x2doptimizer_ApcOptimizer_Ffi(1 /* builtin */);
    if (lean_io_result_is_ok(res)) {
        lean_dec_ref(res);
    } else {
        lean_io_result_show_error(res);
        lean_dec_ref(res);
        abort();
    }
    lean_io_mark_end_initialization();
    g_init_thread = pthread_self();
}

char *leanr_optimize(const char *input) {
    pthread_once(&g_init_once, leanr_do_init);
    pthread_mutex_lock(&g_call_lock);

    int foreign = !pthread_equal(pthread_self(), g_init_thread);
    if (foreign) {
        lean_initialize_thread();
    }

    lean_object *in = lean_mk_string(input);        /* owned */
    lean_object *out = apc_optimizer_optimize_json(in);  /* consumes `in`, returns owned String */
    const char *s = lean_string_cstr(out);
    char *result = strdup(s);
    lean_dec_ref(out);

    if (foreign) {
        lean_finalize_thread();
    }

    pthread_mutex_unlock(&g_call_lock);
    return result;
}

void leanr_free(char *p) {
    free(p);
}
