/*
 * C shim bridging Rust to the apc-optimizer's `@[export] apc_optimizer_optimize_json`.
 *
 * Exposes a plain C ABI:
 *   char *apc_optimizer_optimize(const char *input);   // JSON in -> optimized JSON out (malloc'd)
 *   void  apc_optimizer_free(char *p);                  // free the returned buffer
 *
 * The Lean runtime is initialized exactly once (pthread_once). `apc_optimizer_optimize_json` is a
 * pure `String -> String` with no shared mutable state, and Lean marks all initialization-time
 * constants persistent (RC-exempt) via `lean_io_mark_end_initialization`, so concurrent calls are
 * safe and run without a lock. Each calling thread other than the one that ran initialization is
 * registered with the Lean runtime once (its allocator/thread state), and finalized at thread exit
 * via a pthread-key destructor.
 */
#include <lean/lean.h>
#include <pthread.h>
#include <stdlib.h>
#include <string.h>

/*
 * Generated by Lean for module `ApcOptimizer.Ffi` in the `apc-optimizer` lib. The module-init
 * symbol embeds the lib name with Lean's name mangling (`-` -> `x2d`), and takes a single
 * `builtin` flag (no IO world) in this toolchain, matching the generated `Main.c`. If the apc-optimizer
 * lib/module is renamed, these two symbols change accordingly.
 */
extern lean_object *apc_optimizer_optimize_json(lean_object *input);
extern lean_object *initialize_apc_x2doptimizer_ApcOptimizer_Ffi(uint8_t builtin);

/* Provided by libleanrt. */
extern void lean_initialize_runtime_module(void);
extern void lean_initialize_thread(void);
extern void lean_finalize_thread(void);

static pthread_once_t g_init_once = PTHREAD_ONCE_INIT;
static pthread_t g_init_thread;
/* Non-NULL thread-specific value marks a foreign thread we registered; its destructor finalizes
 * the thread with the Lean runtime when the thread exits. */
static pthread_key_t g_thread_key;

static void finalize_foreign_thread(void *value) {
    (void)value;
    lean_finalize_thread();
}

static void apc_optimizer_do_init(void) {
    lean_initialize_runtime_module();
    lean_object *res = initialize_apc_x2doptimizer_ApcOptimizer_Ffi(1 /* builtin */);
    if (lean_io_result_is_ok(res)) {
        lean_dec_ref(res);
    } else {
        lean_io_result_show_error(res);
        lean_dec_ref(res);
        abort();
    }
    lean_io_mark_end_initialization();
    g_init_thread = pthread_self();
    pthread_key_create(&g_thread_key, finalize_foreign_thread);
}

char *apc_optimizer_optimize(const char *input) {
    pthread_once(&g_init_once, apc_optimizer_do_init);

    /* Register each foreign thread with the runtime once; the pthread-key destructor finalizes it
     * at thread exit. The init thread is already registered by `lean_initialize_runtime_module`. */
    if (!pthread_equal(pthread_self(), g_init_thread) && !pthread_getspecific(g_thread_key)) {
        lean_initialize_thread();
        pthread_setspecific(g_thread_key, (void *)1);
    }

    lean_object *in = lean_mk_string(input);        /* owned */
    lean_object *out = apc_optimizer_optimize_json(in);  /* consumes `in`, returns owned String */
    const char *s = lean_string_cstr(out);
    char *result = strdup(s);
    lean_dec_ref(out);

    return result;
}

void apc_optimizer_free(char *p) {
    free(p);
}
